from __future__ import annotations

CORE_QUEUE = "core"
POSTPROCESS_QUEUE = "postprocess"
ENRICHMENT_QUEUE = "enrichment"
MAINTENANCE_QUEUE = "maintenance"
SHARED_QUEUE = "shared"
WIKI_QUEUE = "wiki"

DOCUMENT_PROCESS_TASK = "document.process"
UPLOAD_FILE_TASK = "upload_file.process"
CHUNK_EXTRACT_TASK = "chunk.extract"
EMBEDDING_INDEX_TASK = "embedding.index"
KNOWLEDGE_POSTPROCESS_TASK = "knowledge.post_process"
SUMMARY_GENERATION_TASK = "summary.generation"
GENERATED_QUESTIONS_TASK = "generated_questions"
IMAGE_MULTIMODAL_TASK = "image.multimodal"
GRAPH_EXTRACTION_TASK = "graph.extraction"
WIKI_INGEST_TASK = "wiki.ingest"
WIKI_FINALIZE_TASK = "wiki.finalize"
DATASOURCE_SYNC_TASK = "datasource.sync"
MAINTENANCE_RECONCILE_TASK = "maintenance.reconcile"
DELETE_CLEANUP_TASK = "delete.cleanup"

TASK_TYPE_TO_QUEUE = {
    DOCUMENT_PROCESS_TASK: CORE_QUEUE,
    UPLOAD_FILE_TASK: CORE_QUEUE,
    CHUNK_EXTRACT_TASK: CORE_QUEUE,
    EMBEDDING_INDEX_TASK: CORE_QUEUE,
    KNOWLEDGE_POSTPROCESS_TASK: POSTPROCESS_QUEUE,
    GRAPH_EXTRACTION_TASK: ENRICHMENT_QUEUE,
    SUMMARY_GENERATION_TASK: ENRICHMENT_QUEUE,
    GENERATED_QUESTIONS_TASK: ENRICHMENT_QUEUE,
    IMAGE_MULTIMODAL_TASK: ENRICHMENT_QUEUE,
    WIKI_INGEST_TASK: WIKI_QUEUE,
    WIKI_FINALIZE_TASK: WIKI_QUEUE,
    DATASOURCE_SYNC_TASK: MAINTENANCE_QUEUE,
    MAINTENANCE_RECONCILE_TASK: MAINTENANCE_QUEUE,
    DELETE_CLEANUP_TASK: MAINTENANCE_QUEUE,
}


def route_for_task_type(task_type: str) -> str:
    return TASK_TYPE_TO_QUEUE.get(str(task_type or "").strip(), SHARED_QUEUE)
